package com.moss.entity;
// Generated 2016-1-21 14:36:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MossImage generated by hbm2java
 */
@Entity
@Table(name = "moss_image", catalog = "moss")
public class MossImage implements java.io.Serializable {

	private Integer id;
	private Integer moss;
	private String link;

	public MossImage() {
	}

	public MossImage(Integer moss, String link) {
		this.moss = moss;
		this.link = link;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "moss")
	public Integer getMoss() {
		return this.moss;
	}

	public void setMoss(Integer moss) {
		this.moss = moss;
	}

	@Column(name = "link", length = 100)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
